Clean up aur-autopush

diff --git a/bin/aur-autopush b/bin/aur-autopush
--- a/bin/aur-autopush
+++ b/bin/aur-autopush
@@ -1,4 +1,26 @@
 #!/bin/bash
+trap 'exit' INT
+function lock
+{
+	local FD LOCKFILE
+	trap no_more_locking EXIT TERM
+	FD=$(shuf -i 1-1000 -n 1)
+	LOCKFILE="${1:-$PWD}/lock.lck"
+	eval "exec $FD>$LOCKFILE"
+	eval "_lock()             { flock -\$1 $FD; }"
+	no_more_locking()
+	{
+		_lock u
+		_lock xn && rm -f "$LOCKFILE"
+		unset _lock
+	}
+	_lock xn || {
+		echo "Failed to lock ${1:-$PWD}"
+		return 1
+	}
+}
+
+# packaging related functions
 function pypi:pkgver
 {
 	curl -s "https://pypi.org/pypi/$1/json" | jq -r '.info.version'
@@ -27,7 +49,7 @@ function py:deps
 
 function pip:deps
 {
-	sed -En "s/^([[:alnum:]]+)==([[:digit:].]+)\.\*,>=([[:digit:].]+)(|; sys_platform == \"linux\")$/python-\1<\2\npython-\1>=\3/p" \
+	sed -En "s/^([[:alnum:]]+)==([[:digit:].]+)\.\*,>=([[:digit:].]+)(|; sys_platform == \"linux\")$/python-\1<\2\npython-\1>=\3/p" "$1" \
 		| awk -F '<|\\.' '$0 ~ /<.*[[:digit:]]$/{print $1"<"$NF+1".0.0"};$0 !~ /<.*[[:digit:]]$/' \
 		| py:deps
 }
@@ -35,9 +57,9 @@ function pip:deps
 function poetry:deps
 {
 	dephell deps convert \
-		--from pyproject.toml \
+		--from ${1:-pyproject.toml} \
 		--to-format=pip \
-		--to-path=stdout 2> /dev/null | pip:deps
+		--to-path=stdout 2> /dev/null | pip:deps -
 }
 
 function pypi:deps
@@ -49,41 +71,7 @@ function pypi:deps
 		| py:deps
 }
 
-function use_vpn
-{
-	local task
-	test -n "$USE_VPN" || return 0
-	[ "$1" = "c" ] || task="dis"
-	echo -ne "vpn: ${task}connecting   \r"
-	false
-	until windscribe "${task}connect" > /dev/null 2>&1; do
-		sleep 1
-	done
-	echo "vpn: ${task}connected   "
-}
-trap 'exit' INT
-function lock
-{
-	local FD LOCKFILE
-	trap no_more_locking EXIT TERM
-	FD=$(shuf -i 1-1000 -n 1)
-	LOCKFILE="${1:-$PWD}/lock.lck"
-	eval "exec $FD>$LOCKFILE"
-	eval "_lock()             { flock -\$1 $FD; }"
-	no_more_locking()
-	{
-		_lock u
-		_lock xn && rm -f "$LOCKFILE"
-		unset _lock
-	}
-	_lock xn || {
-		echo "Failed to lock ${1:-$PWD}"
-		return 1
-	}
-}
-#if ! netcat -zw3 aur.archlinux.org ssh && test -n "$(which --skip-functions --skip-alias windscribe)";then
-#	USE_VPN=true
-#fi
+# script start
 if (($# == 0)); then
 	set -- ./*/
 elif [[ $1 == --stdin ]]; then
@@ -126,12 +114,10 @@ for pkgpath in "$@"; do
 			if git stash push -- . 2> /dev/null | grep -q '^Saved'; then
 				stashed=1
 			fi
-			use_vpn c
 			git pull
 			if ((aurpublish)); then
 				aurpublish -p "$PWD"
 			fi
-			use_vpn d
 			if ((stashed)); then
 				git stash pop > /dev/null 2>&1
 			fi
@@ -206,17 +192,16 @@ for pkgpath in "$@"; do
 			if git status --porcelain --branch | grep -q ahead && {
 				[ ! -f ../.nopush ] || [ "${SKIP_PUSH+defined}" ] && [ "$SKIP_PUSH" != "false" ]
 			}; then
-				use_vpn c
 				git push
 				if ((aurpublish)); then
 					aurpublish "$PWD"
 				fi
-				use_vpn d
 			fi
 			exclude+=(
 				-e '*.log'
 				-e 'PKGBUILD.bak'
 				-e '.no*'
+				-e 'lock.lck'
 			)
 			for src in "${source[@]}"; do
 				src=${src%%::*}
