update bin/*

diff --git a/bin/danime b/bin/danime
--- a/bin/danime
+++ b/bin/danime
@@ -9,7 +9,7 @@
 # shellcheck disable=SC2015
 # shellcheck disable=SC2143
 ((def_header)) && return 0 || def_header=1
-# VERSION r173.0e5a318-1
+# VERSION r178.a3babf5-1
 if [ -f ~/.config/danime.cfg ]; then
 	source ~/.config/danime.cfg
 else
@@ -26,7 +26,6 @@ else
 	RSOLV=3
 	FORCE=
 	SEARCHSTR=
-	TYPE=anime
 	PREFERRED_TR=${PREFERRED_TR:-dub}
 fi
 if [ -n "$AP" ]; then
@@ -408,38 +407,38 @@ da_db()
 da_db_add()
 {
 
-	data="$(jq '. * { "'"$TYPE"'" : {"'"$id"'":{ "title":null ,"path":null,"url":null,"total":null,"saved":null}} }' "$CACHE_FILE")"
+	data="$(jq '. * {"'"$id"'":{ "title":null ,"path":null,"url":null,"total":null,"saved":null}}' "$CACHE_FILE")"
 	da_db_write "$data"
 }
 da_db_list()
 {
-	for type in $(jq -r 'keys|@sh' "$CACHE_FILE" | tr -d \'\"); do
-		for id in $(jq -r '.'"$type"'|keys|[ .[] | tonumber ] | @sh' "$CACHE_FILE"); do
-			echo "$type/$id"
-		done
+	for id in $(jq -r 'keys[] | tonumber | @sh' "$CACHE_FILE"); do
+		echo "$id"
 	done
 }
 da_db_set()
 {
 	if da_db_has; then
-		data="$(jq '.'"$TYPE"'."'"$id"'".'"$1"'='"$2" "$CACHE_FILE")"
+		data="$(jq '."'"$id"'".'"$1"'='"$2" "$CACHE_FILE")"
 		da_db_write "$data"
 	fi
 }
 da_db_get()
 {
 	{
-		jq -re ".$TYPE.\"$id\".$*" "$CACHE_FILE" || echo 0
-	}                                              | tail -1
+		jq -re ".\"$id\".$*" "$CACHE_FILE" || echo 0
+	} | tail -1
 }
+
 da_db_has()
 {
-	jq -e '.'"$TYPE"'."'"$id"'"' "$CACHE_FILE" &> /dev/null
+	jq -e '."'"$id"'"' "$CACHE_FILE" &> /dev/null
 }
+
 da_db_del()
 {
 	if da_db_has; then
-		data="$(jq 'del(."'"$TYPE"'"."'"$id"'")' "$CACHE_FILE")"
+		data="$(jq 'del(."'"$id"'")' "$CACHE_FILE")"
 		da_db_write "$data"
 	fi
 }
@@ -487,15 +486,15 @@ r.cookies = cj
 
 def refine(Str):
 	d={
-		'\''<'\'':'\''＜'\'',
-		'\''>'\'':'\''＞'\'',
-		'\'':'\'':'\''꞉'\'',
-		'\''"'\'':'\''＂'\'',
-		'\''/'\'':'\''⧸'\'',
-		'\''\\'\'':'\''⧹'\'',
-		'\''?'\'':'\''？'\'',
-		'\''|'\'':'\''⫿'\'',
-		'\''*'\'':'\''🞵'\'',
+		"<":"＜",
+		">":"＞",
+		":":"꞉",
+		"\"":"＂",
+		"/":"⧸",
+		"\\":"⧹",
+		"?":"？",
+		"|":"⫿",
+		"*":"🞵",
 	}
 	for n in d.keys():
 		Str=Str.replace(n,d[n])
@@ -503,20 +502,19 @@ def refine(Str):
 try:
 	if len(argv)>1:
 		data = {
-			"model"			:	"'${TYPE:-anime}'".title(),
+			"model"			:	"Anime",
 			"size"			:	200,
 			"what"			:	"query",
 			"letter"		:	"all",
-			"query[order]"	:	"date,asc",
-			"query[search]"	:	str.join(" ", argv[1:])
+			"query"			:	"search=" + " ".join(argv[1:])
 		}
 		try:
-			for n in r.post("https://ww5.dubbedanime.net/ajax/paginate", data).json()['\''results'\'']:
-				print("%s/%s-%s:%s:%s"%('\'${TYPE:-anime}\''.lower(),n['\''id'\''],n['\''slug'\''],0 if not '\''total'\'' in n else n['\''total'\''],refine(n['\''title'\''])))
+			for n in r.post("https://ww5.dubbedanime.net/ajax/paginate", data).json()["results"]:
+				print("%s:%s:%s:%s"%(n["url"],n["id"],0 if not "total" in n else n["total"],refine(n["title"])))
 		except:
 			pass
 except KeyboardInterrupt:
-	pass' "$@"
+	pass' "$@" | sed 's@^/@@'
 
 }
 da_search()
@@ -540,21 +538,15 @@ da_search()
 		vbar
 		vbar "Select One or more to download"
 		vbar
-		echo "$RES" | cut -d: -f2- | awk -F: "{printf \"%-${#total_res}d ) %s\",NR,\$2;if (\$1) {print \" (eps:\"\$1\")\" }else{print \"\"}}"
+		echo "$RES" | cut -d: -f3- | awk -F: "{printf \"%-${#total_res}d ) %s\",NR,\$2;if (\$1) {print \" (eps:\"\$1\")\" }else{print \"\"}}"
 		read -rp$'Download: ' RES_LIST
 	elif ${DOWNLOAD_ALL:-false} && [ -z "$RES_LIST" ]; then
 		RES_LIST='1-'
 	fi
-	if [ -z "$RES_LIST" ]; then
-		vbar
-		vbar "DubbedAnime.net Search Result" true
-		vbar
-		vbar "Select One or more to download"
-		vbar
-		echo "$RES" | cut -d: -f2- | awk -F: "{printf \"%-${#total_res}d ) %s\",NR,\$2;if (\$1) {print \" (eps:\"\$1\")\" }else{print \"\"}}"
-		read -rp$'Download: ' RES_LIST
+	if ! [[ $RES_LIST =~ ^[[:digit:],-]+$ ]]; then
+		RES_LIST=$(echo "$RES_LIST" | sed 's/[^[:digit:],-]/,/g' | tr -s , | sed 's/-,/,/g')
 	fi
-	RES=$(echo "$RES" | cut -d: -f1,3-)
+	RES=$(echo "$RES" | cut -d: -f1,2,4-)
 	RES_LIST=$(expand_limit "$(echo "$RES_LIST" | num_unicode2ascii)" "$total_res")
 	for n in $RES_LIST; do
 		target=$(echo "$RES" | head -n "$n" | tail -1)
@@ -566,7 +558,7 @@ da_search()
 		fi
 		cd "$base" || true
 		local dir
-		dir="$(echo "$target" | cut -d: -f2- | replace_invalid dir)"
+		dir="$(echo "$target" | cut -d: -f3- | replace_invalid dir)"
 		${SKIP_DOWNLOAD:-false} || if [ ! -d "$dir" ]; then
 			rm -f "$dir"
 			mkdir "$dir"
@@ -576,42 +568,60 @@ da_search()
 		}
 		${UPDATE_QUEUE:-false} && vbar
 		echo -e "Title: '$dir'"
-		da_get "$(echo "$target" | cut -d: -f1)" "$dir"
+		da_get "$(echo "$target" | cut -d: -f1)" "$dir" "$(echo "$target" | cut -d: -f2)" "$*"
 		if [ "$(echo "$RES_LIST" | wc -w)" -gt 1 ] && ! $NOBREAK; then
 			read -rsp$'Press Return to download next.'
 			printf '\n'
 		fi
 	done
 }
+
+da_rebuild_db()
+{
+	DO_UPDATE_ONLY=()
+	for id in $(da_db list); do
+		query=$(da_db get query)
+		if [[ $query == 0 ]]; then
+			query=$(da_db get title)
+		fi
+		url=$(da_api_search $query | grep ":$id:" | cut -d: -f1 | tr -d '[:space:]')
+		prev_url=$(da_db get url)
+		if [[ -n $url ]] && [[ $url != "$prev_url" ]]; then
+			echo "Fixing $(da_db get title) [$id]"
+			da_db set url "\"$url\""
+			DO_UPDATE_ONLY+=("$id")
+		elif [[ -z $url ]]; then
+			echo "Failed to fix $(da_db get title) [$id]"
+		fi
+	done
+}
+da_list_queue()
+{
+	for id in $(da_db list); do
+		if ! [ -d "$(da_db get path)" ]; then
+			da_db del
+			continue
+		fi
+		echo "[$id] $(da_db get title)"
+	done
+	return 0
+}
 da_update()
 {
-	local TYPE id dir updatable n new_eps
+	local id dir updatable n new_eps
 	NORESET=true
 	updatable=()
-	if ${DO_UPDATE_LIST:-false}; then
-		for n in $(da_db list); do
-			TYPE="$(dirname $n)"
-			id="$(basename $n)"
+	if (("${#DO_UPDATE_ONLY[@]}" == 0)); then
+		for id in $(da_db list); do
 			if ! [ -d "$(da_db get path)" ]; then
 				da_db del
 				continue
 			fi
-			echo "[$n] $(da_db get title)"
-		done
-		return 0
-	elif (("${#DO_UPDATE_ONLY[@]}" == 0)); then
-		for n in $(da_db list); do
-			TYPE="$(dirname $n)"
-			id="$(basename $n)"
-			if ! [ -d "$(da_db get path)" ]; then
-				da_db del
-				continue
-			fi
-			echo -n "[$n] Checking update..."
-			new_eps=$(($(da_get_len "$n-$(da_db get url)") - $(da_db get saved)))
+			echo -n "[$id] Checking update..."
+			new_eps=$(($(da_get_len "$(da_db get url)") - $(da_db get saved)))
 			if ((new_eps > 0)); then
-				updatable+=("$n")
-				echo -e "\r[$n] Queueing update($new_eps+)..."
+				updatable+=("$id")
+				echo -e "\r[$id] Queueing update($new_eps+)..."
 			else
 				echo
 			fi
@@ -619,9 +629,7 @@ da_update()
 	elif (("${#DO_UPDATE_ONLY[@]}")); then
 		if (("${#DO_UPDATE_ONLY[@]}" > 1)) && [ "${DO_UPDATE_ONLY[0]}" = "!" ]; then
 			DO_UPDATE_ONLY=("$(echo "${DO_UPDATE_ONLY[@]}" | cut -d' ' -f2- | tr -s ' ' '|')")
-			for n in $(da_db list); do
-				TYPE="$(dirname $n)"
-				id="$(basename $n)"
+			for id in $(da_db list); do
 				if echo "$n" | grep -qE "${DO_UPDATE_ONLY[0]}"; then
 					continue
 				fi
@@ -629,35 +637,31 @@ da_update()
 					da_db del
 					continue
 				fi
-				echo -n "[$n] Checking update..."
-				new_eps=$(($(da_get_len "$n-$(da_db get url)") - $(da_db get saved)))
+				echo -n "[$id] Checking update..."
+				new_eps=$(($(da_get_len "$(da_db get url)") - $(da_db get saved)))
 				if ((new_eps > 0)); then
-					updatable+=("$n")
-					echo -e "\r[$n] Queueing update($new_eps+)..."
+					updatable+=("$id")
+					echo -e "\r[$id] Queueing update($new_eps+)..."
 				else
 					echo
 				fi
 			done
 		else
-			for n in "${DO_UPDATE_ONLY[@]}"; do
-				TYPE="$(dirname $n)"
-				id="$(basename $n)"
+			for id in "${DO_UPDATE_ONLY[@]}"; do
 				if da_db has; then
-					updatable+=("$n")
+					updatable+=("$id")
 				fi
 			done
 		fi
 	fi
-	for n in "${updatable[@]}"; do
-		TYPE="$(dirname $n)"
-		id="$(basename $n)"
+	for id in "${updatable[@]}"; do
 		dir="$(da_db get path)"
 		if ! [ -d "$dir" ]; then
 			mkdir -p "$dir" || continue
 		fi
 		cd "$dir" || continue
 		FILE_LIST_RANGE=$(da_db get saved | awk '{print ($0 == "null" || $0 == "0")?"1-":$0"-";}')
-		da_get "$n-$(da_db get url)" "$(basename "$dir")"
+		da_get "$(da_db get url)" "$(basename "$dir")" "$id"
 		if [ "$(da_db get saved)" -ge "$(da_db get total)" ]; then
 			da_db del
 		fi
@@ -682,11 +686,8 @@ set_basedir()
 }
 da_get_len()
 {
-	local series TYPE id type
+	local series type
 	series="$1"
-	TYPE=${series%/*}
-	id=${series%%-*}
-	id=${id##*/}
 	if [ "$series" = "" ]; then
 		return 3
 	fi
@@ -705,37 +706,37 @@ da_get_len()
 }
 da_get()
 {
-	local series TITLE TYPE id ep_slug
+	local series TITLE id ep_slug query
 	unset null_ep_count da_page da_page_json baseurl url epc ep
 	series="$1"
 	TITLE="$2"
-	TYPE=${series%/*}
-	id=${series%%-*}
-	id=${id##*/}
+	id="$3"
 	if [ "$series" = "" ]; then
 		return 3
 	fi
+	query="$4"
 	local ep_progress total_pw
 	if [ -f ".type" ]; then
 		FORCE="$(< .type)"
 	fi
-	start_spinner "Fetching \"$TYPE/$id\" info"
-	da_page=$(curl --config /dev/null "${CURL_OPTIONS[@]}" -ksL "https://ww5.dubbedanime.net/${series%%-*}")
-	da_page_json=$(echo "$da_page" | grep -E '(let|var) (anime|cartoon)' | cut -d= -f2- | cut -d\  -f2- | sed 's/\;$//g' | jq)
-	if [[ $TYPE == anime ]]; then
-		baseurl=$(echo "$da_page" | xmllint --html --nowarning --xpath '//ul[@id="jump-episode"]/node()' - 2> /dev/null | awk '/<li/,/li>/{printf $0;if (++o%3 == 0) print ""}' | while read -rs xml_node; do echo -e "$xml_node" | xmllint --html --nowarning --xpath 'concat("href=",//a/@href,";subbed=",//li/@data-subbed="true" or //li/@data-sub="true",";dubbed=",//li/@data-dubbed="true" or //li/@data-dub="true"," ")' -; done | tr -s ' ' \\n | tac)
-	else
-		baseurl=$(echo "$da_page" | xmllint --html --nowarning --xpath '//*[@id="jump-episode"]/li/node()' - 2> /dev/null | (while read -rs xml_node; do echo "$xml_node" | xmllint --html --nowarning --xpath 'concat("href=",//a/@href," ")' - 2> /dev/null; done) | tr -s ' ' '\n' | grep -v '=$' | tac)
-	fi
+	start_spinner "Fetching \"$id\" info"
+	da_page=$(curl --config /dev/null "${CURL_OPTIONS[@]}" -ksL "https://ww5.dubbedanime.net/$series")
+	da_page_json=$(echo "$da_page" | grep -E '(let|var) anime' | cut -d= -f2- | cut -d\  -f2- | sed 's/\;$//g' | jq)
+	baseurl=$(echo "$da_page" | xmllint --html --nowarning --xpath '//ul[@id="jump-episode"]/node()' - 2> /dev/null | awk '/<li/,/li>/{printf $0;if (++o%3 == 0) print ""}' | while read -rs xml_node; do echo -e "$xml_node" | xmllint --html --nowarning --xpath 'concat("href=",//a/@href,";subbed=",//li/@data-subbed="true" or //li/@data-sub="true",";dubbed=",//li/@data-dubbed="true" or //li/@data-dub="true"," ")' -; done | tr -s ' ' \\n | tac)
 	stop_spinner "$([[ -n $baseurl ]] && echo 0 || echo 1)"
 	if ! {
 		da_db has && ${FILE_LIST:-false}
-	}                          && [ -z "$FILE_LIST_RANGE" ]; then
+	} && [ -z "$FILE_LIST_RANGE" ]; then
 		da_db add
 	fi
 	da_db set path "\"$PWD\""
-	da_db set url "\"$(echo "$da_page_json" | jq -r '.slug')\""
+	da_db set url "\"$series\""
 	da_db set title "\"$TITLE\""
+
+	if [[ -n $query ]]; then
+		da_db set query "\"$query\""
+	fi
+
 	$NORESET || reset
 	${DEBUG:-false} && set -x
 	vbar "$(ellipsis $(($(tput cols) - 10)) "$TITLE")" true
@@ -743,49 +744,45 @@ da_get()
 		tput setaf 1
 		tput dim
 	)No episode is available to download yet.$(tput sgr0)" 1>&2 && exit 1
-	if [[ $TYPE == cartoon ]]; then
-		url="$(echo "$baseurl" | cut -d= -f2-)"
-	else
-		if [[ -n ${PREFERRED_TR:-dub} ]] && [[ -z $FORCE ]]; then
-			tr="$(
-				(
-					echo "$baseurl" | grep -q "${PREFERRED_TR:-dub}bed=true" && echo ${PREFERRED_TR:-dub}
-				) || (
-					echo "$baseurl" | tr \; \\n | grep "$(echo -e 'dub\nsub' | grep -v ${PREFERRED_TR:-dub})bed=true$" | sort -u | cut -d= -f1 | cut -c1-3
-				) || (
-					echo "$baseurl" | tr \; \\n | grep '=true$' | sort -u | cut -d= -f1 | cut -c1-3
-				)
-			)bed"
-		elif [[ -n $FORCE ]]; then
-			tr=${FORCE:0:3}bed
-		elif [ "$(echo "$baseurl" | grep dubbed=true | tr -d '[:space:]')" != "" ]; then
-			tr=dubbed
-		elif [ "$(echo "$baseurl" | grep subbed=true | tr -d "[:space:]")" != "" ]; then
-			tr=$(echo "$baseurl" | tr \; \\n | grep '=true$' | sort -u | cut -d= -f1)
-		fi
-		da_db set type "\"$tr\""
-		url="$(echo "$baseurl" | grep "$tr=true" | cut -d\; -f1 | awk "{print \$0\"-english-$tr\";}")"
-		if ! (echo "$url" | grep -q "${tr}$"); then
-			echo "$(
-				tput setaf 1
-				tput dim
-			)\"$(ellipsis 38 "$TITLE")\" doesn't have any ${tr} episode yet.$(tput sgr0)" 1>&2
-			if ! find . -name '*.mp4' | grep -q '\.mp4$'; then
-				cd ..
-				rm -rf "$OLDPWD"
-			fi
-			if da_db has; then
-				da_db del
-			fi
-			return 1
-		fi
-		url="$(echo "$url" | grep ^href | cut -d= -f2)"
-		for k in $url; do
-			if [ "$(echo "${k##*/}" | cut -d- -f1)" -gt "$(echo "$url" | grep "${k#*-}" | head -1 | xargs basename | cut -d- -f1)" ]; then
-				url="${url//$k/${k//-episode-/-extra-}}"
-			fi
-		done
+	if [[ -n ${PREFERRED_TR:-dub} ]] && [[ -z $FORCE ]]; then
+		tr="$(
+			(
+				echo "$baseurl" | grep -q "${PREFERRED_TR:-dub}bed=true" && echo ${PREFERRED_TR:-dub}
+			) || (
+				echo "$baseurl" | tr \; \\n | grep "$(echo -e 'dub\nsub' | grep -v ${PREFERRED_TR:-dub})bed=true$" | sort -u | cut -d= -f1 | cut -c1-3
+			) || (
+				echo "$baseurl" | tr \; \\n | grep '=true$' | sort -u | cut -d= -f1 | cut -c1-3
+			)
+		)bed"
+	elif [[ -n $FORCE ]]; then
+		tr=${FORCE:0:3}bed
+	elif [ "$(echo "$baseurl" | grep dubbed=true | tr -d '[:space:]')" != "" ]; then
+		tr=dubbed
+	elif [ "$(echo "$baseurl" | grep subbed=true | tr -d "[:space:]")" != "" ]; then
+		tr=$(echo "$baseurl" | tr \; \\n | grep '=true$' | sort -u | cut -d= -f1)
 	fi
+	da_db set type "\"$tr\""
+	url="$(echo "$baseurl" | grep "$tr=true" | cut -d\; -f1 | awk "{print \$0\"-english-$tr\";}")"
+	if ! (echo "$url" | grep -q "${tr}$"); then
+		echo "$(
+			tput setaf 1
+			tput dim
+		)\"$(ellipsis 38 "$TITLE")\" doesn't have any ${tr} episode yet.$(tput sgr0)" 1>&2
+		if ! find . -name '*.mp4' | grep -q '\.mp4$'; then
+			cd ..
+			rm -rf "$OLDPWD"
+		fi
+		if da_db has; then
+			da_db del
+		fi
+		return 1
+	fi
+	url="$(echo "$url" | grep ^href | cut -d= -f2)"
+	for k in $url; do
+		if [ "$(echo "${k##*/}" | cut -d- -f1)" -gt "$(echo "$url" | grep "${k#*-}" | head -1 | xargs basename | cut -d- -f1)" ]; then
+			url="${url//$k/${k//-episode-/-extra-}}"
+		fi
+	done
 	url="$(echo "$url" | sed 's/^\///g')"
 	${DEBUG:-false} && set -x
 	epc=$(echo "$url" | wc -l)
@@ -795,7 +792,7 @@ da_get()
 		return 0
 	}
 	if ${FILE_LIST:-false} && [[ -z $FILE_LIST_RANGE ]]; then
-		[[ $TYPE == cartoon ]] && vbar "ID:$id Files:$epc" || vbar "ID:$id Type:${tr:-dubbed} Files:$epc"
+		vbar "ID:$id Type:${tr:-dubbed} Files:$epc"
 		read -eri "1-$epc" -p$'Episode list: ' FILE_LIST_RANGE
 		ep="$(echo "${FILE_LIST_RANGE:-1-}" | num_unicode2ascii)"
 		tput cuu 2
@@ -828,12 +825,10 @@ da_get()
 		dl_notify="Episode ${ep_show:5}is"
 	fi
 	if [[ -n $ep ]] && [[ -n $ep_show ]]; then
-		[[ $TYPE == cartoon ]] && vbar "ID:$id Files:$epc Downloading:$ep_show" || (
-			vbar "ID:$id Type:${tr:-dubbed}"
-			vbar " Files:$epc Downloading:$ep_show "
-		)
+		vbar "ID:$id Type:${tr:-dubbed}"
+		vbar " Files:$epc Downloading:$ep_show "
 	else
-		[[ $TYPE == cartoon ]] && vbar "ID:$id Files:$epc" || vbar "ID:$id Files:$epc Type:${tr:-dubbed}"
+		vbar "ID:$id Files:$epc Type:${tr:-dubbed}"
 	fi
 	total_pw=$(echo "$ep" | tr \  \\n | wc -l)
 	${DEBUG:-false} && set -x
@@ -926,9 +921,9 @@ da_get_episede()
 			page_url="https://ww5.dubbedanime.net/${d%%-*}"
 			unset d
 		fi
-		parse_episode_page="$(curl --config /dev/null -H "referer: https://ww5.dubbedanime.net/$TYPE/$(da_db get url)" "${CURL_OPTIONS[@]}" -Lks "$1" | grep -E '(var|let) episode')"
+		parse_episode_page="$(curl --config /dev/null -H "referer: https://ww5.dubbedanime.net$(da_db get url)" "${CURL_OPTIONS[@]}" -Lks "$1" | grep -E '(var|let) episode')"
 		if [ -z "$parse_episode_page" ]; then
-			parse_episode_page="$(curl --config /dev/null -H "referer: https://ww5.dubbedanime.net/$TYPE/$(da_db get url)" "${CURL_OPTIONS[@]}" -Lks "$page_url" | grep -E '(var|let) episode')"
+			parse_episode_page="$(curl --config /dev/null -H "referer: https://ww5.dubbedanime.net$(da_db get url)" "${CURL_OPTIONS[@]}" -Lks "$page_url" | grep -E '(var|let) episode')"
 			shift
 			set "$page_url" "$@"
 		fi
@@ -1016,7 +1011,8 @@ da_get_episede()
 			fi
 			ep_file_url=
 			ep_file_host=$(echo "$n" | jq -r '.host')
-			ep_file_id=$(echo "$n" | jq -r '.id' | xargs basename -a)
+			ep_file_id=$(echo "$n" | jq -r '.id' | xargs basename -a 2> /dev/null)
+			[ -z "$ep_file_id" ] && continue
 			set +x
 			start_spinner "Getting url from provider[$ep_file_host:$(ellipsis 15 "$ep_file_id")]"
 			${DEBUG:-false} && set -x
@@ -1095,9 +1091,9 @@ download()
 			elif ((tried <= ${MAX_TRY:-5})); then
 				tput cuu 2
 				((tried > 1)) && (
-					tput    el1
-					tput             el
-					tput                     cuu1
+					tput el1
+					tput         el
+					tput                 cuu1
 				)
 				tput el1
 				tput el
@@ -1137,7 +1133,7 @@ compare_episode()
 		BS=524288
 	fi
 	if [ ! -e "$1" ] || {
-		[          -n "$CHECK_FILE" ] && [ "$CHECK_FILE" == "false" ]
+		[      -n "$CHECK_FILE" ] && [ "$CHECK_FILE" == "false" ]
 	}; then
 		return 0
 	elif [ "$CHECK_FILE" == "error" ]; then
@@ -1393,22 +1389,6 @@ if [[ $# != 0 ]] && [[ $1 != latest ]]; then
 				alias vbar=echo
 				alias stop_spinner=true
 				;;
-			-A)
-				#+option
-				#short: -A
-				#IDNT: 3
-				#text: Set search type to Anime(default).
-				#-option
-				TYPE=anime
-				;;
-			-C)
-				#+option
-				#short: -C
-				#IDNT: 3
-				#text: Set search type to Cartoon.
-				#-option
-				TYPE=cartoon
-				;;
 			-c | --continue)
 				#+option
 				#short: -c
@@ -1523,11 +1503,18 @@ if [[ $# != 0 ]] && [[ $1 != latest ]]; then
 				#IDNT: 2
 				#args: [! ][id1[ id2[ ...]]]
 				#-option
-				DO_UPDATE=true
+				DO_ALT=update
 				if (($# > 1)); then
 					shift
 					DO_UPDATE_ONLY=("$@")
 				fi
+				;;
+			--db-rebuild)
+				#+option
+				#long: --db-rebuild
+				#text: fix/update database metadata.
+				#-option
+				DO_ALT=rebuild-db
 				;;
 			-l | --list)
 				#+option
@@ -1535,7 +1522,7 @@ if [[ $# != 0 ]] && [[ $1 != latest ]]; then
 				#long: --list
 				#text: List updatable/interrupted series.
 				#-option
-				DO_UPDATE_LIST=true
+				DO_ALT=list-queue
 				;;
 			-h | --help)
 				#+option
@@ -1667,7 +1654,7 @@ if [[ $# != 0 ]] && [[ $1 != latest ]]; then
 		echo -e "Warning: --all/-a option can only be used when no\n\tselection or episode limit specified.\n\tDisabling autodownload mode"
 	fi
 	[[ -n $FORCE ]] && echo "${FORCE} enforced."
-	if [[ $SEARCHSTR != '' ]] || ${DO_UPDATE:-false} || ${DO_UPDATE_LIST:-false}; then
+	if [[ $SEARCHSTR != '' ]] || [[ -n $DO_ALT ]]; then
 		if [ -n "$NC" ] || check_up_server dubbedanime.net "${RSOLV:-1}"; then
 			if [ -x "${0%/*}/dubbedanime.scrap" ] && [ -x "$CHROMEDRIVER_PATH" ]; then
 				scrapper_bus=$(
@@ -1693,10 +1680,20 @@ if [[ $# != 0 ]] && [[ $1 != latest ]]; then
 					gdbus call --session --dest "$scrapper_bus" --object-path /scrapper --method "$method" "$@"
 				fi
 			}
-			if ${DO_UPDATE:-false} || ${DO_UPDATE_LIST:-false}; then
-				da_update
-				exit
-			fi
+			case $DO_ALT in
+				update)
+					da_update
+					exit
+					;;
+				list-queue)
+					da_list_queue
+					exit
+					;;
+				rebuild-db)
+					da_rebuild_db
+					exit
+					;;
+			esac
 			if [ -n "$FILE_LIST_RANGE" ] && ! validate_limit "$FILE_LIST_RANGE"; then
 				echo "$(
 					tput setaf 1
