bin/lndl: Add novelget.com support

diff --git a/bin/lndl b/bin/lndl
--- a/bin/lndl
+++ b/bin/lndl
@@ -24,6 +24,8 @@ source_funcs=(
 	al_get
 	al_ls
 	al_sync
+	# novelget.com
+	ng_get
 )
 all_funcs=(
 	"${lib_funcs[@]}"
@@ -180,8 +182,8 @@ function lock
 	no_more_locking()
 	{
 		_lock u
-		_lock      xn && rm -f ./lock.lck
-		unset                                   _lock
+		_lock    xn && rm -f ./lock.lck
+		unset                                 _lock
 	}
 	_lock xn || {
 		echo " ${RED}==>${GREEN} Already updating in another process.$ALL_OFF"
@@ -242,7 +244,7 @@ function drv_get
 	if [[ -z "$2" ]]; then
 		set -- "$1" "$(echo "$JSON" | jq -r .name)"
 		tput cuu1
-		tput         el
+		tput       el
 		echo " $BLUE==>$GREEN Downloading '$(ellipsis $(($(tput cols) - 25)) "${2:-$1}")'...$ALL_OFF"
 	fi
 	set -- "$2" "$1"
@@ -304,13 +306,31 @@ function drv_sync
 	cleanup "${files[@]}"
 }
 
+# novelget.com
+function ng_get
+{
+	local id type name
+	if [[ "$1" =~ ^(epub|mobi|azw3):[a-z0-9]{8}-([a-z0-9]{4}-){3}[a-z0-9]{12}/[[:alnum:]-]*$ ]]; then
+		IFS=:/ read -r type id name <<< $1
+		read -r id < <(
+			curl --disable -sIXGET "https://novelget.com/download/$id/" \
+				| read_header location \
+				| sed -E 's@^.*/\*/([[:alnum:]_-]+)\?.*$@\1@'
+		)
+		drv_get "$id" "$name.$type"
+	else
+		echo >&2 "Invalid Source"
+		return 1
+	fi
+}
+
 # Armaell Library
 function al_get
 {
 	local size HEADER try target etarget action data
 	echo " $BLUE==>$GREEN Downloading '$(ellipsis $(($(tput cols) - 25)) "$1")'...$ALL_OFF"
 	until [ "$(echo "$HEADER" | http_code)" = "200" ]; do
-		HEADER=$(curl -kLsIXGET "$2")
+		HEADER=$(curl --disable -kLsIXGET "$2")
 	done
 	size="$(echo "$HEADER" | read_header content-length)"
 	date="$(echo "$HEADER" | read_header last-modified | xargs --null date +%s -d)"
@@ -442,7 +462,7 @@ else
 			unset "${all_funcs[@]}"
 			echo "ERROR: Unsupported command '$1'"
 			show_help
-			exit                                                                                         1
+			exit                                                                                       1
 			;;
 	esac
 fi
